### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alair069** [NetherTechnology/BedWars#5]
Error: syntax error, unexpected '$this' (T_VARIABLE)
File: /plugins/BedWars-master/src/Bluplayz/BedWars
Line: 85
Type: notice

**Comment by KitrosMC** [comment]
I will fix in soon
Thank for your report

**Comment by KitrosMC** [comment]
Fixed

**Comment by alair069** [comment]
![image](https://user-images.githubusercontent.com/27539870/28475415-7732d214-6e22-11e7-9226-1370155bca58.png)
The error still continues to be insisted ..
